# Examen Primera Convocatoria

In [2]:
# Your imports HERE !!!!
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 01 - 1 pt
- Dado un array de elementos, escribir una función, que reciba dicho array como parámetro de entrada y devuelva el elemento repetido. Usando plain Python, sin ninguna librería.

In [16]:
array_src = [4, 8, 0, 3, 6, 2, 1, 5, 3, 9, 7]
expected_rep_element = 3
rep_element = repeated_element(array_src) # This calls your function repeated_element
assert(expected_rep_element == rep_element)  # This will fail if the element is not found correctly

In [15]:
# Your solution HERE !!!!
def repeated_element(array):
    repetido = []
    for i in array:    
        if i not in repetido:
            repetido.append(i)
        else:
            return i

## 02 - 1pt
- Genera una matriz con valores aleatorios de 0 a 100 de dimensiones 16x16
- Calcula los siguentes estadísticos en la matriz anterior, por fila (el resultado de cada uno debe ser un array de dimensiones 1x16)
  - Suma de los elementos de cada fila
  - Media de los elementos de cada fila
  - Valores mínimos de cada fila
  - Valores máximos de cada fila

In [120]:
# Your solution HERE !!!!
matriz = np.random.randint(100,size=(16,16))
suma = np.sum(a=matriz, axis=1)
minimo = np.min(a=matriz, axis=1)
maximo = np.max(a=matriz, axis=1)
media = np.mean(a=matriz, axis=1)

print(matriz)
print(suma)
print(minimo)
print(maximo)
print(media)

[[41 67 59 84 54 90 99 65 29 20 64 43 16 44 83 80]
 [19  8 43  2 12 28 24  2 57  6  5 11 87 97 99  8]
 [95 44 90 63 98 27 67 87 66  6 74 22 35 47 36 30]
 [76 82 65  7 72 93 67 52  1 78 86 84 70 53 92 13]
 [91 73 24  2 31  6 24 25  6 93 47 48  5 96 33 78]
 [95 72 98 10  6 94 36 48  8  0 59  6 81 99 25 75]
 [86 59 21 38 73 94 58 80 33 47 19 80 74 13 37  5]
 [64  8 90 79 93  6 69 88 48  3 92 70 60 22 55 47]
 [96 77  1 87 68 59 26  1 59 21 38 12 40 44 17 55]
 [70  5 51 18 87 69 16 40 21 33 67 54 49 53 79  5]
 [11 82 90 80 81 12 34 88 11 98 86 45 68 15 86 44]
 [26 63 57 34 14 79 30  5 41 73 37 45 22  2 35 82]
 [31 81  9 88 79 98 46 30 17 38 22 75 98 18 75 64]
 [89 26 76 56 62 44  8 84 11 35 62 24 33 87 60 90]
 [55 18 27 25 13 49 44  4 73 95 23 76 26 85 70 31]
 [86 87 65 66 69 91 64 19  5 91 61 14 66 93 95 33]]
[ 938  508  887  991  682  812  817  894  701  717  931  645  869  847
  714 1005]
[16  2  6  1  2  0  5  3  1  5 11  2  9  8  4  5]
[99 99 98 93 96 99 94 93 96 87 98 82 98 90 95 95]


## 03 - 1pt

- Generar un dataframe de 3x4 dimensiones con valores númericos aleatorios [0,10]
- Darle un índice semántico alfanumérico
- Aplicarle una función lambda que obtenga la diferencia entre el máximo y mínimo de cada fila

In [49]:
# Your solution HERE !!!!
matriz = np.random.randint(0,11, size=(3,4))
df = pd.DataFrame(matriz , index=list('ABC'))
display(df)
print(df.apply(lambda x : x.max() - x.min(), axis = 1)) 

0  1   2  3
A  7  0   6  3
B  0  3   3  8
C  7  5  10  6

A    7
B    8
C    5
dtype: int64


## 04 - 1pt
- Crear un array de NumPy de dimensiones 8x5, con números enteros aleatorios en el rango [-100, 100]
- Ejecutar en este orden
  - Reemplazar valores  
    - Reemplazar los valores de todos aquellos números múltiplos de 5 por 100
    - Reemplazar los valores de todos aquellos números múltiplos de 3 por Nan
   
  - Averiguar cuantos elementos tienen Nan por fila
  - Reemplazar los valores de Nan por 0

In [75]:
# Your solution HERE !!!!
matrix = np.random.randint(-100,100, size=(8,5))
print(matrix)

matrix_1 = np.where(matrix % 5 == 0, 100, matrix)
print(matrix_1)

matrix_2 = np.where(matrix_1 % 3 == 0, np.nan, matrix_1)
print(matrix_2)

print(np.isnan(matrix_2).sum(axis = 1))

matrix_3 = np.where(np.isnan(matrix_2), 0, matrix_2)
print(matrix_3)

[[  80   82   12   88  -82]
 [  31   56  -44   52   93]
 [ -69   89  -99  -38 -100]
 [ -60  -59  -63  -54    0]
 [ -41   19  -60  -58   75]
 [  -6   -8  -44   -8   50]
 [  21  -38  -47  -64   97]
 [  27   44  -40 -100   86]]
[[100  82  12  88 -82]
 [ 31  56 -44  52  93]
 [-69  89 -99 -38 100]
 [100 -59 -63 -54 100]
 [-41  19 100 -58 100]
 [ -6  -8 -44  -8 100]
 [ 21 -38 -47 -64  97]
 [ 27  44 100 100  86]]
[[100.  82.  nan  88. -82.]
 [ 31.  56. -44.  52.  nan]
 [ nan  89.  nan -38. 100.]
 [100. -59.  nan  nan 100.]
 [-41.  19. 100. -58. 100.]
 [ nan  -8. -44.  -8. 100.]
 [ nan -38. -47. -64.  97.]
 [ nan  44. 100. 100.  86.]]
[1 1 2 2 0 1 1 1]
[[100.  82.   0.  88. -82.]
 [ 31.  56. -44.  52.   0.]
 [  0.  89.   0. -38. 100.]
 [100. -59.   0.   0. 100.]
 [-41.  19. 100. -58. 100.]
 [  0.  -8. -44.  -8. 100.]
 [  0. -38. -47. -64.  97.]
 [  0.  44. 100. 100.  86.]]


## 05 - 1pt
- Crear una función que reciba una lista de strings y devuelva una serie de pandas, y convierta el primer y último carácter de la palabra de cada elemento de la serie a mayúsculas

In [ ]:
languages = ['python', 'php', 'java', 'javascript', 'c++', 'sql']
expected_output = pd.Series(['PythoN', 'PhP', 'JavA', 'JavascripT', 'C++', 'SqL'])
output = first_last_uppercase(languages)  # This calls your function first_last_uppercase
assert(expected_output.equals(output))  # This will fail if the two lists are different

In [86]:
# Your solution HERE !!!!
# def first_last_uppercase(languages):
languages = ['python', 'php', 'java', 'javascript', 'c++', 'sql']

languagesS = pd.Series(languages)
df[0] = df[0].apply(lambda x: str(x)[-1].capitalize()) 
display(languagesS)

for i in languages:
    i.capitalize
    i.apply(lambda x: x.capitalize()) 

languagesS = pd.Series(languages)

0        python
1           php
2          java
3    javascript
4           c++
5           sql
dtype: object

## 06 - 3 pt
- Se tienen cuatro datasets, se adjuntan sus datos como diccionarios
  - Orders, representa un conjunto de pedidos, con sus fechas, su cantidad, y el cliente y vendedor asociados al mismo
  - Customers, conjunto de clientes, con su nombre y su ciudad
  - Salesman, conjunto de vendedores, con su nombre, ciudad y porcentaje de comisión por venta
  - Cities, conjunto de ciudades con sus nombres
- Obtener la siguiente información usando Pandas
  - El nombre del vendedor con la mejor venta, y a que cliente ha sido
  - Dinero de la comisión otorgada para cada pedido, ordenado por fechas
  - Media del dinero de los pedidos de los clientes de Tokyo
  - Total del dinero de las comisiones del vendedor Ikuzu Midoriya en el mes de Agosto
- Representar graficamente
  - Media del total de cada pedido para cada cliente agrupado por ciudad
  - Línea temporal del total de los pedidos

In [87]:
orders = {'OrderId': [1,2,3,4,5,6], 'OrderDate': ['2021-07-23', '2021-08-06', '2021-07-28', '2021-08-04', '2021-08-03', '2021-07-30'], 'Amount': [1500.5,2000.65,1550.2,1900.75,2205.4, 1208.22], 'CustomerId': [3,4,2,2,1,4], 'SalesmanId': [3,3,2,1,3,2]}
customers = {'CustomerId': [1,2,3,4], 'Name': ['Brad Davis', 'Julian Green', 'Geoff Cameron', 'Fabian Johnson'], 'CityId': [2,1,2,3]}
salesmans = {'SalesmanId': [1,2,3], 'Name': ['James Knite', 'Reinhardt Wilhelm', 'Ikuzu Midoriya'], 'CityId': [1,3,2], 'Comission': [0.15,0.11,0.09]}
cities = {'CityId': [1,2,3], 'Name': ['New York', 'Tokyo', 'Berlin']}

In [111]:
# Your solution HERE !!!!
ordenes = pd.DataFrame(orders)
clientes = pd.DataFrame(customers)
vendedores = pd.DataFrame(salesmans)
ciudades = pd.DataFrame(cities)

a = ordenes.merge(vendedores, on='SalesmanId', how='inner')
b = a.merge(clientes, on='CustomerId', how='inner')

# El nombre del vendedor con la mejor venta, y a que cliente ha sido
maximo_ventas = b['Amount'].max()
display(maximo_ventas)
# print('El vendedor con más ventas: '+ b['Amount'].max())
# Dinero de la comisión otorgada para cada pedido, ordenado por fechas
# Media del dinero de los pedidos de los clientes de Tokyo
# Total del dinero de las comisiones del vendedor Ikuzu Midoriya en el mes de Agosto
display(b)

display(ordenes)
display(clientes)
display(vendedores)
display(ciudades)

2205.4

OrderId   OrderDate   Amount  CustomerId  SalesmanId             Name_x  \
0        1  2021-07-23  1500.50           3           3     Ikuzu Midoriya   
1        2  2021-08-06  2000.65           4           3     Ikuzu Midoriya   
2        6  2021-07-30  1208.22           4           2  Reinhardt Wilhelm   
3        5  2021-08-03  2205.40           1           3     Ikuzu Midoriya   
4        3  2021-07-28  1550.20           2           2  Reinhardt Wilhelm   
5        4  2021-08-04  1900.75           2           1        James Knite   

   CityId_x  Comission          Name_y  CityId_y  
0         2       0.09   Geoff Cameron         2  
1         2       0.09  Fabian Johnson         3  
2         3       0.11  Fabian Johnson         3  
3         2       0.09      Brad Davis         2  
4         3       0.11    Julian Green         1  
5         1       0.15    Julian Green         1

OrderId   OrderDate   Amount  CustomerId  SalesmanId
0        1  2021-07-23  1500.50           3           3
1        2  2021-08-06  2000.65           4           3
2        3  2021-07-28  1550.20           2           2
3        4  2021-08-04  1900.75           2           1
4        5  2021-08-03  2205.40           1           3
5        6  2021-07-30  1208.22           4           2

CustomerId            Name  CityId
0           1      Brad Davis       2
1           2    Julian Green       1
2           3   Geoff Cameron       2
3           4  Fabian Johnson       3

SalesmanId               Name  CityId  Comission
0           1        James Knite       1       0.15
1           2  Reinhardt Wilhelm       3       0.11
2           3     Ikuzu Midoriya       2       0.09

CityId      Name
0       1  New York
1       2     Tokyo
2       3    Berlin

## 07 - 1pt
- Escribir un generador `frange` que simule el comportamiento de la función `arange` de NumPy
- Esta función cada vez que se invoque debe devolver valores espaciados uniformemente a partir de un valor inicial. Se debe proveer a dicha función un valor inicial para la secuencia de números y un valor para el step
- Debe soportar valores númericos en coma flotante
- La función potencialmente se puede llamar un número infinito de veces
- Usando plain Python, sin ninguna librería

In [ ]:
import math

init = 10.6
step = 0.8
g = frange(init, step)  # This calls your function frange

iters = 10
numbers = [next(g) for n in range(iters)]
for i, n in enumerate(numbers):
    assert(math.isclose(n, init + (step * i)))  # This will fail if the range is not properly created

In [ ]:
# Your solution HERE !!!!

## 08 - 1pt
- Crear una lista de meses de Enero a Diciembre (eje X)
- Generar datos aleatorios para el eje Y, hacerlo 3 veces distintas (Y0, Y1 e Y2)
- Representar las 3 secuencias de datos aleatorios en una sola figura usando matplotlib
- Añadir una leyenda para poder identificar cada secuencia
- Nombrar las 3 secuencias de la siguiente manera ("Facebook", "Twitter", "Instagram")
- Añadir un título y nombres a los dos ejes
- Añadir una anotación (texto y flecha) a uno de los gráficos

In [ ]:
# Your solution HERE !!!!